# Generated by Django 3.2.9 on 2021-11-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('numero_celular', models.CharField(max_length=13)),
                ('estado', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
    ]
