# Generated by Django 3.2.9 on 2021-11-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0002_auto_20211106_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
    ]
